// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_buttons': string;
  '_groupContainer': string;
  '_groupContent': string;
  '_groupHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
