// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_active': string;
  '_logoutButton': string;
  '_mainName': string;
  '_mainUsername': string;
  '_sidebarContainer': string;
  '_sidebarContent': string;
  '_sidebarHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
