// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_buttonContent': string;
  '_deleteButton': string;
  '_editButton': string;
  '_pagination': string;
  '_perPage': string;
  '_selected': string;
  '_tableBody': string;
}
export const cssExports: CssExports;
export default cssExports;
