// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_page': string;
  '_pageContent': string;
}
export const cssExports: CssExports;
export default cssExports;
