// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_buttonLogin': string;
  '_error': string;
  '_loginContainer': string;
  '_loginContent': string;
}
export const cssExports: CssExports;
export default cssExports;
